# Site settings
title: AI Talks
email: christianfullerton@icloud.com
description: >-
  Exploring the future of artificial intelligence, one post at a time.

# GitHub Pages config
baseurl: "/AI-Blog"                     # Needed for GitHub Pages project sites
url: "https://cfull03.github.io"       # Your GitHub Pages base URL

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Markdown engine behavior (optional but safe)
kramdown:
  parse_block_html: true

# Minima theme customization
minima:
  skin: dark
