# Site settings
title: AI Talks
email: your-email@example.com
description: >-
  Exploring the future of artificial intelligence, one post at a time.

# You are hosting from a GitHub project repo: https://cfull03.github.io/AI-Blog
baseurl: "/AI-Blog"       # Needed for GitHub Pages project sites
url: "https://cfull03.github.io"  # Your GitHub Pages base URL

twitter_username: ""
github_username: cfull03

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Minima theme customization
minima:
  skin: dark

# Optional: exclude build files
# exclude:
#   - Gemfile
#   - Gemfile.lock
